name: 'Feature Request'
description: 'Suggest a new feature or enhancement.'
title: '[Feature] '
labels: ['enhancement']
assignees:
  - oluizeduardo
body:
  - type: textarea
    id: description
    attributes:
      label: 'Feature Description'
      description: 'Explain in detail what the feature does and why it is useful.'
    validations:
      required: true

  - type: textarea
    id: task-breakdown
    attributes:
      label: 'Task Breakdown'
      description: 'List the steps or sub-tasks needed to implement this feature.'

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 'Acceptance Criteria'
      description: 'Define the conditions that must be met for this feature to be considered complete.'

  - type: textarea
    id: additional_context
    attributes:
      label: 'Additional Context'
      description: 'Any extra information, considerations, or links that might help in implementing this feature.'
